- name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Instalador-Acesso-Livre
        # Mudamos o caminho para buscar qualquer APK gerado
        path: "**/build/outputs/apk/debug/*.apk"
