name: Acesso Livre

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Permissão no Gradlew
        # Isso garante que o script que você colou tenha poder de execução
        run: chmod +x gradlew

      - name: Build APK com Gradle
        # Esse comando vai compilar seu Java/Kotlin e criar o instalador
        run: ./gradlew assembleDebug

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Acesso-Livre-Final
          # Caminho padrão onde o Android gera o arquivo
          path: app/build/outputs/apk/debug/*.apk
